# ---
# include:
# - "**/*.rb"
# exclude:
# - spec/**/*
# - test/**/*
# - vendor/**/*
# - ".bundle/**/*"
# require: []
# domains: []
# reporters:
# - rubocop
# - require_not_found
# plugins: []
# require_paths: []
# max_files: 5000

include:
  - "app/**/*.rb"
  - "config/**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
# Ruby on Rails のサポートを強化するための設定
# 完全な入力補完が実現できるわけではないが、設定をしないよりは少し使えるようになる
# 参照: https://github.com/castwide/solargraph/issues/87
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
# lint の設定
# ここでは rubocop を使用する想定の設定をしている
reporters:
  - rubocop
